name: tracker

services:
  tracker-storage:
    image: postgres:16-alpine
    container_name: tracker-storage
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=p4ssw0rd
    ports:
      - 5432:5432
    networks:
      - tracker-network
    volumes:
      - tracker-data:/var/lib/postgresql/data

volumes:
  tracker-data:
    driver: local
    name: tracker-data

networks:
  tracker-network:
    driver: bridge
    name: tracker-network
